version: "3"

services:
  web:
    build: .
    volumes:
      - .:/code
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    #entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    env_file: env_files/local
    stdin_open: true
    tty: true
